export const LAUNCHES_LISTING_LOADING = `LAUNCHES_LISTING_LOADING`;
export const LAUNCHES_LISTING_DONE = `LAUNCHES_LISTING_DONE`;
export const LAUNCHES_LISTING_ERROR = `LAUNCHES_LISTING_ERROR`;

export const CHANGE_LAUNCH_YEAR_FILTER = `CHANGE_LAUNCH_YEAR_FILTER`;
export const CHANGE_SUCCESSFUL_LAUNCH_FILTER = `CHANGE_SUCCESSFUL_LAUNCH_FILTER`;
export const CHANGE_SUCCESSFUL_LAND_FILTER = `CHANGE_SUCCESSFUL_LAND_FILTER`;

export const INITIAL_FILTERS_SET = `INITIAL_FILTERS_SET`;
